services:
  docs:
    build:
      context: .
      target: docs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    command:
      - /bin/sh
      - -c
      - |
        echo ''
        echo '-------------------------------------------------------'
        echo ' Docs preview will be available at:'
        echo '   http://localhost:8000'
        echo '-------------------------------------------------------'
        echo ''
        exec sphinx-autobuild source build --host 0.0.0.0 --port 8000

  qgis:
    profiles:
      - qgis
    build:
      context: .
      target: qgis-enmapbox
    environment:
      DISPLAY: ${DISPLAY:-}
      QT_QPA_PLATFORM: xcb
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command:
      - qgis
