name: Build documentation

on: [push, pull_request]

jobs:
  build:
    name: Build Sphinx docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 --version
        pip install -U -r requirements.txt
        pip list
        pwd
    - name: Run Sphinx
      run: |
        sphinx-build -b html -j auto --nitpicky source build

