name: Build documentation

on: [push, pull_request]

jobs:
  build:
    name: Build Sphinx docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        python3 --version
        pip list
        pip install -U -r requirements.txt
        pwd
    - name: Run Sphinx
      run: |
        sphinx-build -b html -j auto -W source build

