name: Check RST Style

on: [push, pull_request]

jobs:
  build:
    name: Check RST Style
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 --version
        pip list
        pip install -U -r requirements.txt
        pwd
    - name: Run doc8
      run: |
        doc8 source

