name: Check URLs

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: urls-checker
        uses: urlstechie/urlchecker-action@master
        with:
          file_types: .md,.py,.rst
          # Choose whether to include file with no URLs in the prints.
          print_all: false
          timeout: 20
          retry_count: 3
          verbose: true
          force_pass: false
          exclude_files: /scripts/create_external_link_file.py,/source/dev_section/external_links.rst
          exclude_patterns: https://enmap-box.readthedocs.io/en/latest/general/glossary.html,https://tiles.wmflabs.org,https://fbinter.stadt-berlin.de/fb/wfs,https://github.com/conda-forge/miniforge/releases/latest/download/
          exclude_urls: http://localhost:8000/,https://github.com/mygithubaccount/enmap-box-documentation-fork.git,https://www.gnu.org/licenses/gpl-3.0.en.html,https://www.gnu.org/licenses/,https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh
